name: Build and Deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: vertex-ai-summarizer-neha
  GCR_LOCATION: us-central1
  GCE_INSTANCE: vertex-ai-vm
  GCE_INSTANCE_ZONE: us-central1-a

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    # Configure Docker to use gcloud as a credential helper
    - run: |-
        gcloud --quiet auth configure-docker
        
    # Build the Docker image
    - name: Build
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/vertex-ai-summarizer:$GITHUB_SHA" .
        
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/vertex-ai-summarizer:$GITHUB_SHA"
        
    # Deploy to Google Compute Engine
    - name: Deploy
      run: |-
        gcloud compute ssh --quiet --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE --command "
          # Pull the latest image
          docker pull gcr.io/$PROJECT_ID/vertex-ai-summarizer:$GITHUB_SHA &&
          
          # Stop existing container
          docker stop vertex-ai-api || true &&
          docker rm vertex-ai-api || true &&
          
          # Run new container
          docker run -d \
            --name vertex-ai-api \
            -p 8000:8000 \
            -v ~/secrets:/app/secrets:ro \
            -v ~/.env:/app/.env:ro \
            --restart unless-stopped \
            gcr.io/$PROJECT_ID/vertex-ai-summarizer:$GITHUB_SHA
        "